app:
  port: 9000
  host: "0.0.0.0"

logging:
  level: "info"
  
database:
  host: "localhost"
  port: "5434"
  name: "navigator"
  schema: "public"
  username: "postgres"
  password: "postgres"
  max_connections: 100
  min_connections: 5
  connect_timeout: 8
  acquire_timeout: 8
  idle_timeout: 8
  max_lifetime: 8
  sqlx_logging: true